[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ["py36"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
[tool.isort]
profile = "black"
line_length = 100
[build-system]
requires = [
    "requests>=2.24",
    "toml>=0.10.2",
    "urllib3>=1.24.2",
    "pyxdg>=0.26",
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
